
POST http://localhost:3000/api/login
Content-Type: application/json
Accept: application/json

{
    "username": "john",
    "password": "gehheim"
}
###

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer

{
    "username": "llls",
    "password": "gehheim",
    "firstname": "Lisa",
    "lastname": "Simpson",
    "email": "lisa@simpson.com"
}
###

GET http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTg2MTM2NjEsImlkIjoxLCJ1c2VybmFtZSI6ImpvaG4iLCJmaXJzdG5hbWUiOiJKb2huIiwibGFzdG5hbWUiOiJEb2UiLCJpYXQiOjE1NTg2MTMwNjF9.EHbpR_dH_Uz8riFkMe5o4qDtLmUwdns_5xdgN2-QR7Q

###

GET http://localhost:3000/api/users/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTY3NDQwMDYsImlkIjoxLCJ1c2VybmFtZSI6ImpvaG4iLCJmaXJzdG5hbWUiOiJKb2huIiwibGFzdG5hbWUiOiJEb2UiLCJpYXQiOjE1NTY3NDM0MDZ9.aSaeu42JeHwnJaVmAE3HjvkI0B_UpklA3JZyf-1K5pA
###
